publishDir = "docs"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Elm Workshop"
theme = "docdock"
uglyurls = true
relativeURLs = true
ignoreFiles = [ "elm-stuff$" ]

[params]
  editURL = "https://github.com/sporto/elm-workshop"
  description = "Elm Workshop"
  author = "Sebastian Porto"
  autoNav = true
  noHomeIcon = true
  noSearch = true

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/sporto/elm-workshop"
weight = 10